apiVersion: v1
kind: Service
metadata:
  name: devs-tracker-server
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: devs-tracker-server
