CREATE SCHEMA IF NOT EXISTS devstracker AUTHORIZATION devstracker;
ALTER DEFAULT PRIVILEGES IN SCHEMA devstracker GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO devstracker;
ALTER DEFAULT PRIVILEGES IN SCHEMA devstracker GRANT USAGE, SELECT ON SEQUENCES TO devstracker;

SET ROLE devstracker;

CREATE TABLE IF NOT EXISTS users (
    u_id BIGSERIAL PRIMARY KEY,
    u_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    u_token VARCHAR(128) UNIQUE NOT NULL,
    u_device VARCHAR(256) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS aliases (
    a_id BIGSERIAL PRIMARY KEY,
    a_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    a_token VARCHAR(128) UNIQUE NOT NULL,
    a_user_id BIGINT NOT NULL REFERENCES users(u_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS developers (
    d_id BIGSERIAL PRIMARY KEY,
    d_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    d_apple_id BIGINT UNIQUE NOT NULL,
    d_name VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS trackers (
    t_id BIGSERIAL PRIMARY KEY,
    t_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    t_user_id BIGINT NOT NULL REFERENCES users(u_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    t_developer_id BIGINT NOT NULL REFERENCES developers(d_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    t_last_view TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(t_user_id, t_developer_id)
);

CREATE TABLE IF NOT EXISTS checks (
    c_id BIGSERIAL PRIMARY KEY,
    c_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    c_developer_id BIGINT NOT NULL REFERENCES developers(d_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    c_country VARCHAR(2) NOT NULL,
    c_priority INTEGER DEFAULT 0 NOT NULL,
    c_last_check TIMESTAMPTZ NOT NULL DEFAULT TIMESTAMPTZ 'epoch',
    UNIQUE(c_developer_id, c_country)
);

CREATE TABLE IF NOT EXISTS apps (
    a_id BIGSERIAL PRIMARY KEY,
    a_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    a_apple_id BIGINT UNIQUE NOT NULL,
    a_release_date TIMESTAMPTZ NOT NULL,
    a_developer_id BIGINT NOT NULL REFERENCES developers(d_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS links (
    l_id BIGSERIAL PRIMARY KEY,
    l_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    l_app_id BIGINT NOT NULL REFERENCES apps(a_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    l_title VARCHAR(256) NOT NULL,
    l_country VARCHAR(2) NOT NULL,
    l_url VARCHAR (512) NOT NULL,
    UNIQUE(l_app_id, l_country)
);

CREATE TABLE IF NOT EXISTS notifications (
    n_id BIGSERIAL PRIMARY KEY,
    n_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    n_developer_id BIGINT NOT NULL REFERENCES developers(d_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    n_app_apple_id BIGINT UNIQUE NOT NULL,
    n_app_title VARCHAR(128) NOT NULL,
    n_processed BOOLEAN NOT NULL DEFAULT FALSE,
    n_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);