version: '3'

services:
  devs-tracker-db:
    image: postgres:13
    container_name: devs-tracker-db
    restart: always
    volumes:
      - ../src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./devs-tracker-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_USER=devstracker
      - POSTGRES_DB=devstracker