server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
logging:
  level:
    root: WARN
    com.zaxxer.hikari: INFO
    com.crionuke.devstracker: ${LOGGING_LEVEL_COM_CRIONUKE_DEVSTRACKER}
devsTracker:
  validateRequests: ${DEVS_TRACKER_VALIDATE_REQUESTS}
  freeTrackersLimit: ${DEVS_TRACKER_FREE_TRACKERS_LIMIT}
  maxTrackersLimit: ${DEVS_TRACKER_MAX_TRACKERS_LIMIT}
api:
  firebase:
    credentialsJson: "${API_FIREBASE_CREDENTIALS_JSON}"
  revenueCat:
    secretKey: ${API_REVENUE_CAT_SECRET_KEY}